Replacing python cosmology component by TensorFlow
modichirag/flowpm pull request #56
Opened 2020-11-12 15:39 UTC by dlanzieri

We implemented tfbackground and some tests . This pullrequest solves the issues #46

2020-11-12 15:49 UTC, dlanzieri commented
Test has failed because of the missing TensorFlow Probability @EiffL

2020-11-12 18:19 UTC, EiffL commented
Hi @dlanzieri , I've found the reason why your tests were never returning :-) It's because you had some plotting functions in the `tfbackground.py` file. Everytime you import that tfbackground like this:
```python
import flowpm.tfbackground as tfbackground
```
it runs all of the commands it finds in the file, so in your case, it was running the plotting functions. In general you only want to have functions and/or classes definitions in a module file like tfbackground.py.

You can still add a section at the bottom of the file with plotting instructions to make some plots/tests, but you want to add a  declaration like this before:
```python
if __name__ == "__main__":
```
This tells Python to only run these instructions if you are trying to execute the file like a script, i.e. run `python flowpm/tfbackground.py`, and these instructions will be ignored if you simply import the file.

I have made a small modification on my last commit to move the plotting instructions under this section.  I have also added the necessary things to the `setup.py` to make sure tensorflow_probability gets installed automatically for the tests on travis CI.

You can see the contents of commits by clicking on the last commit above named `Fix testing issues`, or by clicking [here](https://github.com/modichirag/flowpm/pull/56/commits/3dfc6bad346e6e923f1c5d2877d46c47382e8624)

All the tests are working on my machine :-D
```
[francois@Mizar flowpm]$ pytest 
========================================= test session starts ==========================================
platform linux -- Python 3.8.6, pytest-6.1.1, py-1.9.0, pluggy-0.13.1
rootdir: /home/francois/repo/flowpm, configfile: pytest.ini
collected 14 items                                                                                     

tests/test_tfpm.py ......                                                                        [ 42%]
tests/test_utils.py ...                                                                          [ 64%]
tests/tf_background_test.py .....                                                                [100%]

========================================= 14 passed in 11.87s ==========================================
```

To make sure that you have all of the necessary tools installed on your computer to run all the tests, you should try to reintstall flowpm with the following command:
```bash
$ pip install --user -e .[testing]
```
note the `[testing]` section, which tells pip to install the dependencies necessary for testing, like the fastpm code we are using to compare to.

2020-11-27 22:12 UTC, EiffL reviewed
I've done a full pass through the PR and left a few comments, it's looking good so far :-) Most of my comments are related to the documentation. 
One thing I notice is that we have a lot of functions like Gp gp D1, etc with names that are not explicit and these functions are even sometimes redundant, we should try to see what is the mininum set of funcntions we need for flowpm

2020-11-27 22:12 UTC, EiffL commented on flowpm/tfbackground.py
> +    a=tf.convert_to_tensor(a,dtype=tf.float32)
missing documentation

2020-11-27 22:12 UTC, EiffL commented on flowpm/tfbackground.py
> +    a=tf.convert_to_tensor(a,dtype=tf.float32)
missing documentation

2020-11-27 22:12 UTC, EiffL commented on flowpm/tfbackground.py
> +def Gp(cosmo, a):
This function is redundant with D1 :-/ we should remove one of them

2020-11-27 22:12 UTC, EiffL commented on flowpm/tfbackground.py
> +    FastPM growth factor function
what is the difference with Gp? Needs better documentattion

2020-11-27 22:12 UTC, EiffL commented on flowpm/tfbackground.py
> +    Derivative of Gf against a
This should have a better description that doesnt reference another function

2020-11-27 22:12 UTC, EiffL commented on flowpm/tfbackground.py
> +            a : tf.TensorArray
missing cosmo

2020-11-27 22:12 UTC, EiffL commented on flowpm/tfbackground.py
> +    Derivative of Gf2 against a
same comment as above, needs better description

2020-11-27 22:12 UTC, EiffL commented on flowpm/tfbackground.py
> +            a : tf.TensorArray
missing cosmo

2020-11-27 22:12 UTC, EiffL commented on flowpm/tfbackground.py
> +# if __name__ == "__main__":
We can keep this main section and use it to plot a few things for tests if that's useful. If not useful, we sshould remove all of this commented section

2020-11-27 22:12 UTC, EiffL commented on flowpm/tfpower.py
> +def sigmasqr(cosmo, R, transfer_fn, kmin=0.0001, kmax=1000.0, ksteps=5, **kwargs):
either hide that function from imports.... or improve documentation

2020-11-27 22:12 UTC, EiffL commented on setup.py
> +        'testing':  ['fastpm', 'pyccl'],
we should try to remove this dependency on pyccl, nbodykit has functions for cosmology computations, we can use those

2020-11-27 22:12 UTC, EiffL commented on tests/test_tfpower.py
> +import pyccl as ccl
replace pyccl by nbodykit

2020-11-29 19:37 UTC, EiffL commented on setup.py
> +        'testing':  ['fastpm', 'pyccl'],
removed dependency on pyccl and switched to nbodykit

2020-11-29 19:37 UTC, EiffL commented on tests/test_tfpower.py
> +import pyccl as ccl
done as well

2020-11-29 19:42 UTC, EiffL commented
Thanks for the updates @dlanzieri  :-) When you address a comment, you can leave a message in the "Reply" box below the comment, and if you believe the comment is fully addressed you can "resolve conversation", if you are not sure that you can fully address the comment, or if you disagree, you can respond to it and we only resolve the conversation when we both agree on the comment.

I have just addressed one of my comments which was about not using `pyccl` as a reference for testing the Eisenstein Hu power spectrum, and instead I'm now using `nbodykit` which is already a dependency of the code.

2020-11-30 23:58 UTC, EiffL commented
oups, looks like your tests are failing ^^^^

2020-12-01 13:49 UTC, EiffL commented
Fantastic!!! I just had a look and it looks great! So happy to see all of the pieces come together!

I have a few additional suggestions:

- [ ] : you can completely replace the old `tfpm.py` with the content of your `denise_tfpm.py` and you can keep the same function names. Don't worry about replacing things :-)
The code in `tfpm.py` is being tested against an external reference (python-fastpm) in this test:
https://github.com/modichirag/flowpm/blob/tfcosmo/tests/test_tfpm.py
So you can modify the content of `tfpm.py`, and these tests will tell you if you have broken something. You can see how these tests are coded, and you can try to run your own fastpm simulation if you want to have a point of reference of what a "correct code" does.

- [ ] : you can rename the old `baground.py` as `legacy_background.py` to make clear that it's not used for anything anymore, except maybe testing.

- [ ] : I see that your commit messages are a bit long, for instance, this is what appears on github:
![image](https://user-images.githubusercontent.com/861591/100748077-2bc73380-33e3-11eb-804e-686f86b0b38a.png)
The idea is that commit messages can be kept short, they should be about what this commit changes in the code and you can commit often so that you don't have one massive commit.
You can provide more details about the modifications you have made in this PR thread for instance. 

- [ ] : You can see if you go this PR thread on GitHub that the automated tests are failing after your commit from yesterday. It appears in several places, next to the PR name in the list:
![image](https://user-images.githubusercontent.com/861591/100748468-a42df480-33e3-11eb-9734-6dc4ff211e89.png)
(it's the red cross)
You can see it after each individual commits if they pass the tests or not in this thread:
![image](https://user-images.githubusercontent.com/861591/100748596-cb84c180-33e3-11eb-9bbc-feab7cc36d08.png)
For instance you see there that I made a bunch of broken commits before finding how to fix the bug.
And you can see it at the end of the thread there:
![image](https://user-images.githubusercontent.com/861591/100748691-ebb48080-33e3-11eb-87fc-8bf15eb64ad5.png)
This is the place you want to look at to find out what's wrong, if you click on:
- `Details`
- Then on the `The build` link here:
![image](https://user-images.githubusercontent.com/861591/100748811-228a9680-33e4-11eb-848d-31c4adf11c9c.png)
It will send you to Travis CI, and you will see a page like this of Travis trying to run the tests:
![image](https://user-images.githubusercontent.com/861591/100748920-45b54600-33e4-11eb-8207-884d72079775.png)
and here we see that the tests are failing because you have removed the Gp function.

Sorry for the long message ^^' Just wanted to give you a few extra-tips on GitHub

2020-12-03 22:36 UTC, EiffL requested changes
I have noticed a few mistakes, nothing major, but otherwise looks good :-)

2020-12-03 22:36 UTC, EiffL commented on flowpm/tfpm.py
> +def lpt_init(linear, a, af,n_steps,order=2, cosmology=cosmo, kvec=None, name="LPTInit"):
This is not correct! `lpt_init` does not have af and n_steps parameters

2020-12-03 22:36 UTC, EiffL commented on flowpm/tfpm.py
> +    a = a
we can remove this line, it's not doing anything

2020-12-03 22:36 UTC, EiffL commented on flowpm/tfpm.py
> +    #pt = PerturbationGrowth(cosmology, a=[a], a_normalize=1.0)
remove this line

2020-12-03 22:36 UTC, EiffL commented on flowpm/tfpm.py
> +    X = tf.add(DX, Q)
what is this doing here ^^' ? Looks like a copy/paste of the same lines above

2020-12-03 22:36 UTC, EiffL commented on flowpm/tfpm.py
> +    fac = 1. / (ac ** 3 * E(cosmo,ac)) * (D1(cosmo,af) - D1(cosmo,ai)) / D1f(cosmo,ac)
ok great, but does that mean we don't need the Gp and gp functions in `background.py`?

2020-12-03 22:36 UTC, EiffL commented on tests/test_tfpm.py
> +  tfread = tfpm.lpt_init(tlinear, a0, af,n_steps, order=1).numpy()
so here we should remove af and n_steps

2020-12-03 22:36 UTC, EiffL commented on tests/test_tfpm.py
> +  af = 1.0
also don't need this here

2020-12-03 22:36 UTC, EiffL commented on tests/test_tfpm.py
> +  n_steps=10
same. let's remove this

2020-12-03 22:36 UTC, EiffL commented on tests/test_tfpm.py
> +  state = tfpm.lpt_init(tlinear, a0, af,n_steps, order=1)
remove af and nsteps

2020-12-07 16:16 UTC, EiffL reviewed
Looking good, ready for review I think

2020-12-07 16:21 UTC, EiffL commented
Hi @modichirag ! could you take a look at this PR and tell us what you think? It should replace all of the old python code with a cool new Tensorflow implementation of all cosmology functions!

2020-12-07 16:22 UTC, EiffL approved these changes

2020-12-09 15:59 UTC, modichirag commented
This is brilliant. Thank you @dlanzieri and @EiffL for doing this. I have 2 comments that I would like your opinion on before we merge this (though it can be merged now as well) -

1. the major difference from previous version in terms of UI I see is that some tfpm functions take in a cosmology dictionary.
Of all tfpm functions, I think - nbody, lpt_init and linear_field will be called externally while others will likely not be (atleast for an end-to-end pm simulation). Of these, only linear_field does not take in the cosmo dict, but a interpolated 'pk'. My question is this - do we want to make 'pk' part of the cosmology object so that all three functions have consistent signature in terms of comsology dependence? It might also be easier in terms of implementing differentiability w.r.t. cosmology parameters since pk will also depend on them, though then we might be constrained to use Eisenstein Hu? 
So maybe we can keep things as they are right now, giving more flexibility of providing a different interpolated power spectrum instead of constraining ourselves.
What do you guys think?

2. do we want to check for differentiability with respected to some cosmology parameters in one of the tests before merging or should we work on that after things are setup, and that the gradients match? No reason why they would not though, so maybe this is not required at this stage. 

Thanks again for this extensive PR.

2020-12-09 18:48 UTC, merged

2020-12-09 18:49 UTC, modichirag reviewed
Looks good :)